# Generated by Django 5.1.7 on 2025-04-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibeGroup',
            fields=[
                ('Group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=20)),
                ('Description', models.TextField(default='No Description Provided', max_length=500)),
                ('Group_Pic', models.ImageField(default='default_images/smiling-cube.png', upload_to='group_images')),
                ('Creation_date', models.DateField()),
                ('Is_private', models.BooleanField(default=False)),
                ('Member_count', models.IntegerField(default=1)),
            ],
        ),
    ]
