# Generated by Django 5.1.7 on 2025-04-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vibegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibegroup',
            name='Group_Pic',
            field=models.ImageField(default='group-images/smiling-cube.png', upload_to='group_images'),
        ),
    ]
