# Generated by Django 5.1.7 on 2025-04-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vibegroup_group_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibegroup',
            name='Group_Pic',
            field=models.ImageField(default='smiling-cube.png', upload_to='group_images'),
        ),
    ]
