# Generated by Django 5.1.7 on 2025-04-20 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vibegroup_group_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vibegroup',
            old_name='Group_Pic',
            new_name='group_pic',
        ),
        migrations.RenameField(
            model_name='vibegroup',
            old_name='Group_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vibegroup',
            old_name='Is_private',
            new_name='is_private',
        ),
        migrations.RenameField(
            model_name='vibegroup',
            old_name='Member_count',
            new_name='member_cnt',
        ),
        migrations.RemoveField(
            model_name='vibegroup',
            name='Creation_date',
        ),
        migrations.RemoveField(
            model_name='vibegroup',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='vibegroup',
            name='Name',
        ),
        migrations.AddField(
            model_name='vibegroup',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vibegroup',
            name='description',
            field=models.CharField(default='No Description Provided', max_length=500),
        ),
        migrations.AddField(
            model_name='vibegroup',
            name='name',
            field=models.CharField(default='GroupName', max_length=20),
            preserve_default=False,
        ),
    ]
