# Generated by Django 5.1.7 on 2025-04-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_group_pic_vibegroup_group_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibegroup',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
