# Generated by Django 5.1.7 on 2025-04-21 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vibeuser_banner_pic_vibeuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibepost',
            name='comment_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vibepost',
            name='share_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='VibeComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField(blank=True, null=True)),
                ('media', models.ImageField(blank=True, null=True, upload_to='post-media')),
                ('date_time_posted', models.DateTimeField(auto_now_add=True)),
                ('like_cnt', models.IntegerField(default=0)),
                ('share_cnt', models.IntegerField(blank=True, default=0, null=True)),
                ('comment_cnt', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_replied_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vibepost')),
            ],
        ),
    ]
